### ISSUE TITLE
Correct branding for SAP AI Core and SAP AI Launchpad 

### ISSUE THREAD

**Issue by anirban-sap** [SAP-samples/smart-co2nverter-ai#6]
Could you please use the correct branding for SAP AI Core and SAP AI Launchpad: 

https://discovery-center.cloud.sap/serviceCatalog/sap-ai-core
https://discovery-center.cloud.sap/serviceCatalog/sap-ai-launchpad

**Comment by jmsrpp** [comment]
Updated in markdown and merged with DC.
